#ifndef __INDEXES_H__
#define __INDEXES_H__

#define BASICS_ID_INDEX 0
#define BASICS_TYPE_INDEX 1
#define BASICS_TITLE_INDEX 2
#define BASICS_IS_ADULT_INDEX 4
#define BASICS_RUNTIME_INDEX 7

#define RATINGS_ID_INDEX 0
#define RATINGS_RATING_INDEX 1
#define RATINGS_NUM_VOTES_INDEX 2

#define DATA_ID_INDEX 0
#define DATA_PARENT_ID_INDEX 1

#define AKAS_ID_INDEX 0
#define AKAS_TITLE_INDEX 2
#define AKAS_REGION_INDEX 3

#endif